---
services:
    mysql:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "@OR0Yhy@@NvC3aYd70="
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql:/var/lib/mysql

volumes:
    mysql:
