---
services:
    mysql:
        image: mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql:/var/lib/mysql

volumes:
    mysql:
