---
services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - db:/data
        command: redis-server --appendonly no
volumes:
    db:
